### ISSUE TITLE
what is './mstcn_data/50salads/splits/all_files.txt'?

### ISSUE THREAD

**Issue by daidaiershidi** [dipika-singhania/ICC-Semi-Supervised-TAS#1]
FileNotFoundError: [Errno 2] No such file or directory: './mstcn_data/50salads/splits/all_files.txt'.

Looking forward to your reply.

**Comment by daidaiershidi** [comment]
This file also does not exist in the https://drive.google.com/drive/folders/15WHW0yHMG1MZJG_uOKeEZNYqZktYXLca.

**Comment by dipika-singhania** [comment]
Hi, 

all_files.txt was the file containing all the files of 50salads.
I had forgotten to upload it. I have updated google drive with it.
You can download it.
