### ISSUE TITLE
Fail to reproduce the results for 50salads

### ISSUE THREAD

**Issue by tqosu** [dipika-singhania/ICC-Semi-Supervised-TAS#2]
Hi Dipika,

I used your implement code and weights for the 50salads dataset. But the results were much worse than that in the paper.

Do you know how to fix this?

Implementation results
5% 41.7 & 36.1 & 25.7 & 38.9 & 55.0
10% 61.1 & 55.6 & 42.0 & 52.3 & 65.8

results in the paper
5% 52.9 49.0 36.6 45.6 61.3
10% 67.3 64.9 49.2 56.9 68.6

**Comment by dipika-singhania** [comment]
Please download the unsupervised checkpoint again.
Also, update the runcodes semi-supervised scripts and then try to run the whole thing again.
There was a hyper-parameter which was hard coded to constant value.
It would be replicated.

**Comment by tqosu** [comment]
Hi Dipika,

Thanks.👍 I will have a try.

Best,
Tieqiao
