### ISSUE TITLE
dataset split

### ISSUE THREAD

**Issue by hitcbw** [dipika-singhania/ICC-Semi-Supervised-TAS#5]
Hi singhania,
    Thanks for your excellent work. I noticed that when generating semi-supervision on 50salads, the 2 or 3 samples in activity ID 1 first be chosen and another 23 samples in activity 2 are chosen. Why do you make this setting? Did I miss some explanation :)?

**Comment by dipika-singhania** [comment]
I didn't make this setting intentionally. It was random selection with videos from the 2 different types of salads mentioned in the dataset.
