### ISSUE TITLE
Questions abount chunk design

### ISSUE THREAD

**Issue by tyler8812** [dipika-singhania/ICC-Semi-Supervised-TAS#6]
Hi Dipika,

First, thanks for the contribution for such a great work.
I am trying to go through the code and implement it.
I was wondering what is the reason for reducing the frame numbers of a video with the chunk size in the dataset.py?

https://github.com/dipika-singhania/ICC-Semi-Supervised-TAS/blob/e0b1544cce56b899345c175e91c127d0333df878/dataset.py#L79

Is it for making the training faster?
Or for the same size of the feature?

BR,
Tyler

**Comment by dipika-singhania** [comment]
Chunk Size is required for doing temporal feature augmentation. This is a feature of the base C2F-TCN model [(Described in Section 3.3)](https://arxiv.org/pdf/2105.10859.pdf) of the paper. Even Appendix Section C of our [ICC](https://arxiv.org/pdf/2112.01402.pdf) paper describes it in the short section Downsampling. 

Temporal Feature Augmentation has the advantage of improving scores and additionally increasing training speed chunk size time per iteration. Detailed explanation is given in the C2FTCN paper.
